#!/usr/bin/env python3
"""Byte-compare the published vectors against the reference implementation's copy.

CONFORMANCE.md Section 7 says the vectors are generated by a reference implementation
and published here. Two copies therefore exist, in two repositories, and they are
byte-identical only because someone kept them so by hand. A single flipped byte on
either side would mean the suite a verifier is measured against is not the suite the
generator produces, which is the one drift that would quietly invalidate conformance.

Usage:
    python scripts/check_vector_drift.py --flynn ../flynn
    FLYNN_DIR=../flynn python scripts/check_vector_drift.py

Exits non-zero on any difference, listing every file that differs, is missing, or is
present on only one side.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Published suite -> the same suite inside the reference implementation.
SUITE_PAIRS = [
    ("vectors/structural", "chain/conformance/testdata/vectors"),
    ("vectors/crypto", "chain/conformance/testdata/crypto"),
]


def digests(root: Path) -> dict[str, str]:
    """sha256 of every file under root, keyed by its path relative to root."""
    return {
        str(p.relative_to(root)).replace("\\", "/"): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--flynn",
        default=os.environ.get("FLYNN_DIR"),
        help="path to a checkout of the reference implementation (or set FLYNN_DIR)",
    )
    args = parser.parse_args()

    if not args.flynn:
        print("error: pass --flynn <path> or set FLYNN_DIR", file=sys.stderr)
        return 2
    flynn = Path(args.flynn).resolve()
    if not flynn.is_dir():
        print(f"error: {flynn} is not a directory", file=sys.stderr)
        return 2

    problems: list[str] = []
    compared = 0

    for published_rel, upstream_rel in SUITE_PAIRS:
        published, upstream = REPO / published_rel, flynn / upstream_rel
        if not published.is_dir():
            problems.append(f"{published_rel} does not exist in this repository")
            continue
        if not upstream.is_dir():
            problems.append(
                f"{upstream_rel} does not exist in {flynn}. If the reference "
                "implementation moved its vectors, update SUITE_PAIRS in this script."
            )
            continue

        here, there = digests(published), digests(upstream)
        compared += len(here)

        for name in sorted(set(here) - set(there)):
            problems.append(f"{published_rel}/{name}: published here, absent upstream")
        for name in sorted(set(there) - set(here)):
            problems.append(f"{upstream_rel}/{name}: present upstream, not published here")
        for name in sorted(set(here) & set(there)):
            if here[name] != there[name]:
                problems.append(
                    f"{published_rel}/{name}: differs from upstream "
                    f"(here {here[name][:12]}, upstream {there[name][:12]})"
                )

    if problems:
        print(f"vector drift detected ({len(problems)} problem(s)):\n")
        for problem in problems:
            print(f"  - {problem}")
        print(
            "\nThe published suite and the generator disagree. Regenerate from the "
            "reference implementation and republish, or fix whichever side moved."
        )
        return 1

    print(f"no vector drift: {compared} files byte-identical across both repositories")
    return 0


if __name__ == "__main__":
    sys.exit(main())
